### ISSUE TITLE
Resizing a window causes the window to move around the screen

### ISSUE THREAD

**Issue by 9898287** [gort818/ddgtk#4]
Is it something about [this](https://developer.gnome.org/gtk3/stable/GtkWindow.html#GtkWindowPosition)?

https://my.mixtape.moe/ldndxm.webm

master branch

I'm using GNOME 3.30.2

**Comment by gort818** [comment]
Wow that is strange, I cannot reproduce. Will do some testing on different DEs.

**Comment by gort818** [comment]
I think you are right, thanks for that. Can you give it a try now?

**Comment by 9898287** [comment]
Fixed, as a side note, I would like it more if the "start" button did not actually fill up the space given to it. 
![](https://i.imgur.com/z8iavLY.png)

And the subtle horizontal list separator lines don't look so nice either.

But it's functional now. Now I'll see if I can make this into an appimage

**Comment by gort818** [comment]
Yeah good idea it definitely needs a redesign.

**Comment by gort818** [comment]
What do you think about having the start button in the header bar, seems like a lot of Gnome programs are moving functionality to the header bar.

**Comment by 9898287** [comment]
Well If I were to give my opinion, the start button going upto the headerbar does not make much sense. The users starts out with the filechooserbutton, then the combobox below and the other combobox which beneath the previous one. The natural placement for the trigger button now is at the very bottom of the window.
